Create patient test cases
pavankumar017/playwright-housewroks pull request #4
Opened 2024-02-09 06:26 UTC by RuchetaG

2024-02-09 09:51 UTC, pankaj51 approved these changes

2024-02-09 10:22 UTC, pavankumar017 requested changes

2024-02-09 10:22 UTC, pavankumar017 commented on hw-e2e/create-patient.spec.ts
> +  await page.goto(`${baseURL}`);
I guess this goto is not needed - Since - in Global setup the login is done

2024-02-12 04:12 UTC, RuchetaG commented on hw-e2e/create-patient.spec.ts
> +  await page.goto(`${baseURL}`);
Global setup logs in and saves credentials for future use. To be able to login we need to go to the login page. Hence, this step is required.

2024-02-12 05:21 UTC, pavankumar017 approved these changes

2024-02-12 09:34 UTC, merged